// <auto-generated />
using System;
using Hrguedes.Localize.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hrguedes.Localize.Infra.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240730174748_relationships")]
    partial class relationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hrguedes.Localize.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnName("Documento");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("VARCHAR(800)")
                        .HasColumnName("Endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(800)")
                        .HasColumnName("Nome");

                    b.Property<bool>("RegistroAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("RegistroAtivo");

                    b.Property<DateTime>("RegistroCriado")
                        .HasColumnType("DATETIME")
                        .HasColumnName("RegistroCriado");

                    b.Property<DateTime?>("RegistroRemovido")
                        .HasColumnType("DATETIME")
                        .HasColumnName("RegistroRemovido");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnName("Telefone");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("DATETIME")
                        .HasColumnName("UltimaAtualizacao");

                    b.HasKey("Id");

                    b.ToTable("Clientes", "Operacao");
                });

            modelBuilder.Entity("Hrguedes.Localize.Domain.Entities.Cobranca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("INT");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataVencimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1200)")
                        .HasColumnName("Descricao");

                    b.Property<bool>("Pago")
                        .HasColumnType("BIT")
                        .HasColumnName("Pago");

                    b.Property<bool>("RegistroAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("RegistroAtivo");

                    b.Property<DateTime>("RegistroCriado")
                        .HasColumnType("DATETIME")
                        .HasColumnName("RegistroCriado");

                    b.Property<DateTime?>("RegistroRemovido")
                        .HasColumnType("DATETIME")
                        .HasColumnName("RegistroRemovido");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("DATETIME")
                        .HasColumnName("UltimaAtualizacao");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Cobrancas", "Operacao");
                });

            modelBuilder.Entity("Hrguedes.Localize.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(355)")
                        .HasColumnName("Nome");

                    b.Property<bool>("RegistroAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("RegistroAtivo");

                    b.Property<DateTime>("RegistroCriado")
                        .HasColumnType("DATETIME")
                        .HasColumnName("RegistroCriado");

                    b.Property<DateTime?>("RegistroRemovido")
                        .HasColumnType("DATETIME")
                        .HasColumnName("RegistroRemovido");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("Senha");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("DATETIME")
                        .HasColumnName("UltimaAtualizacao");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", "Sistema");
                });

            modelBuilder.Entity("Hrguedes.Localize.Domain.Entities.Cobranca", b =>
                {
                    b.HasOne("Hrguedes.Localize.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Cobrancas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Hrguedes.Localize.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Cobrancas");
                });
#pragma warning restore 612, 618
        }
    }
}
